# Generated by Django 4.1.3 on 2022-11-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('fatigue', models.IntegerField(default=0)),
                ('nausea', models.IntegerField(default=0)),
                ('bloated', models.IntegerField(default=0)),
                ('dairy', models.IntegerField(default=0)),
                ('gluten', models.IntegerField(default=0)),
                ('sugar', models.IntegerField(default=0)),
                ('daySlug', models.SlugField(default='day-', unique=True)),
            ],
        ),
    ]
